import Effect from "src/game/value-objects/effect";
import Skill from "src/game/value-objects/skill";

const buffSkills = [
  new Skill({
    id: "buff_001",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    cooldown: 0,
    effects: new Effect({
      id: "effect_009",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { str: 1 },
      duration: 5,
    }),
    metadata: {
      name: "War Shout",
      text: "Increase STR +1",
      rarity: "common",
    },
  }),
  new Skill({
    id: "buff_002",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    cooldown: 0,
    effects: new Effect({
      id: "effect_008",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { int: 1 },
      duration: 5,
    }),
    metadata: {
      name: "Great Intellect",
      text: "Increase INT +1",
      rarity: "common",
    },
  }),
  new Skill({
    id: "buff_003",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    cooldown: 0,
    effects: new Effect({
      id: "effect_007",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { wis: 1 },
      duration: 5,
    }),
    metadata: {
      name: "Wisdom Chant",
      text: "Increase WIS +1",
      rarity: "common",
    },
  }),
  new Skill({
    id: "buff_004",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    cooldown: 0,
    effects: new Effect({
      id: "effect_006",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { con: 1 },
      duration: 5,
    }),
    metadata: {
      name: "Iron Body",
      text: "Increase CON +1",
      rarity: "common",
    },
  }),
  new Skill({
    id: "buff_005",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    cooldown: 0,
    effects: new Effect({
      id: "effect_005",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { sta: 1 },
      duration: 5,
    }),
    metadata: {
      name: "Endurance Cry",
      text: "Increase STA +1",
      rarity: "common",
    },
  }),
  new Skill({
    id: "buff_006",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    cooldown: 0,
    effects: new Effect({
      id: "effect_004",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { dex: 1 },
      duration: 5,
    }),
    metadata: {
      name: "Precision Focus",
      text: "Increase DEX +1",
      rarity: "common",
    },
  }),
  new Skill({
    id: "buff_007",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    cooldown: 0,
    effects: new Effect({
      id: "effect_003",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { agi: 1 },
      duration: 5,
    }),
    metadata: {
      name: "Agile Step",
      text: "Increase AGI +1",
      rarity: "common",
    },
  }),
  new Skill({
    id: "buff_008",
    rank: 1,
    typeSkill: "buff",
    reach: "global",
    effects: new Effect({
      id: "effect_002",
      target: "self",
      effectType: "buff",
      mechanic: "refresh",
      subtype: "attribute",
      scaling: { cha: 1 },
      duration: 5,
    }),
    metadata: {
      name: "Charisma Aura",
      text: "Increase CHA +1",
      rarity: "common",
    },
  }),
];

export default buffSkills;
