const buffSkills = [
  {
    rank: 1,
    name: "War Shout",
    type: "buff",
    reach: "global",
    text: "Increase STR +1",
    rarity: "common",
    buff: { str: 1 },
  },
  {
    rank: 1,
    name: "Great Intellect",
    type: "buff",
    reach: "global",
    text: "Increase INT +1",
    rarity: "common",
    buff: { int: 1 },
  },
  {
    rank: 1,
    name: "Wisdom Chant",
    type: "buff",
    reach: "global",
    text: "Increase WIS +1",
    rarity: "common",
    buff: { wis: 1 },
  },
  {
    rank: 1,
    name: "Iron Body",
    type: "buff",
    reach: "global",
    text: "Increase CON +1",
    rarity: "common",
    buff: { con: 1 },
  },
  {
    rank: 1,
    name: "Endurance Cry",
    type: "buff",
    reach: "global",
    text: "Increase STA +1",
    rarity: "common",
    buff: { sta: 1 },
  },
  {
    rank: 1,
    name: "Precision Focus",
    type: "buff",
    reach: "global",
    text: "Increase DEX +1",
    rarity: "common",
    buff: { dex: 1 },
  },
  {
    rank: 1,
    name: "Agile Step",
    type: "buff",
    reach: "global",
    text: "Increase AGI +1",
    rarity: "common",
    buff: { agi: 1 },
  },
  {
    rank: 1,
    name: "Charisma Aura",
    type: "buff",
    reach: "global",
    text: "Increase CHA +1",
    rarity: "common",
    buff: { cha: 1 },
  },
];

export default buffSkills;
