import BuffSkill from "src/game/gcomponents/skills/buffSkill";

const buffSkills = [
  new BuffSkill({
    id: "buff_001",
    rank: 1,
    name: "War Shout",
    type: "buff",
    reach: "global",
    text: "Increase STR +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { str: 1 },
    duration: 10,
  }),
  new BuffSkill({
    id: "buff_002",
    rank: 1,
    name: "Great Intellect",
    type: "buff",
    reach: "global",
    text: "Increase INT +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { int: 1 },
    duration: 10,
  }),
  new BuffSkill({
    id: "buff_003",
    rank: 1,
    name: "Wisdom Chant",
    type: "buff",
    reach: "global",
    text: "Increase WIS +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { wis: 1 },
    duration: 10,
  }),
  new BuffSkill({
    id: "buff_004",
    rank: 1,
    name: "Iron Body",
    type: "buff",
    reach: "global",
    text: "Increase CON +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { con: 1 },
    duration: 10,
  }),
  new BuffSkill({
    id: "buff_005",
    rank: 1,
    name: "Endurance Cry",
    type: "buff",
    reach: "global",
    text: "Increase STA +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { sta: 1 },
    duration: 10,
  }),
  new BuffSkill({
    id: "buff_006",
    rank: 1,
    name: "Precision Focus",
    type: "buff",
    reach: "global",
    text: "Increase DEX +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { dex: 1 },
    duration: 10,
  }),
  new BuffSkill({
    id: "buff_007",
    rank: 1,
    name: "Agile Step",
    type: "buff",
    reach: "global",
    text: "Increase AGI +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { agi: 1 },
    duration: 10,
  }),
  new BuffSkill({
    id: "buff_008",
    rank: 1,
    name: "Charisma Aura",
    type: "buff",
    reach: "global",
    text: "Increase CHA +1",
    rarity: "common",
    typeBuff: "attribute",
    buff: { cha: 1 },
    duration: 10,
  }),
];

export default buffSkills;
